title: "Discover Seoul and Busan: A Budget-Friendly Adventure"
description: "Embark on an unforgettable journey through Seoul and Busan with our comprehensive guide tailored for travelers on a budget"
show_downloads: true
google_analytics:
#baseurl: "/dinky" # the subpath of your site, e.g. /blog

# Build settings
theme: jekyll-theme-dinky
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-toc
  - jekyll-tagging
#plugins:
#  - jekyll-feed
#  - jekyll-sitemap
#  - jekyll-toc

# Exclude these from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

#collections:
#  markdown_files:
#    output: true
#    permalink: /:collection/:name

#collections:
#  markdown_files:
#    output: true
#    permalink: /:name

collections:
  markdown_files:
    output: true
    permalink: /:collection/:name
